const config=window.SITE_CONFIG||{};const menuData=window.MENU_DATA||{};const reservationConfig=window.RESERVATION_CONFIG||{};
const getValue=(source,path)=>path.split('.').reduce((value,key)=>value?.[key],source);
document.querySelectorAll('[data-config]').forEach(e=>{const v=getValue(config,e.dataset.config);if(v!==undefined)e.innerHTML=v});
document.querySelectorAll('[data-config-href]').forEach(e=>{const v=getValue(config,e.dataset.configHref);if(v)e.href=`mailto:${v}`});
if(config.seo){document.title=config.seo.title||document.title;const d=document.querySelector('meta[name="description"]');if(d&&config.seo.description)d.content=config.seo.description}
if(config.theme){const m={accent:'--accent',accentHover:'--accent-hover',dark:'--dark',darkSoft:'--dark-soft',textOnDark:'--text-on-dark',mutedOnDark:'--muted-on-dark',paper:'--paper',paperSoft:'--paper-soft',text:'--text',mutedText:'--muted-text',card:'--card',border:'--border',borderStrong:'--border-strong',buttonText:'--button-text',overlay:'--overlay',selection:'--selection',accentSoft:'--accent-soft',input:'--input',map:'--map',footer:'--footer',borderDark:'--border-dark',focus:'--focus'};Object.entries(m).forEach(([k,v])=>{if(config.theme[k])document.documentElement.style.setProperty(v,config.theme[k])});if(config.theme.headingFont)document.documentElement.style.setProperty('--font-heading',`'${config.theme.headingFont}',serif`);if(config.theme.bodyFont)document.documentElement.style.setProperty('--font-body',`'${config.theme.bodyFont}',sans-serif`)}
if(config.hero?.image){const e=document.querySelector('.hero-image');if(e)e.style.backgroundImage=`url("${config.hero.image}")`}
function renderMenu(){const grid=document.querySelector('.menu-grid');if(!grid||!Array.isArray(menuData.dishes))return;grid.innerHTML=menuData.dishes.map((d,i)=>`<article class="dish-card ${i===0?'featured-dish':''}"><div class="dish-image" style="background-image:url('${d.image}')" role="img" aria-label="${d.name}"></div><div class="dish-info"><span>${d.category}</span><h3>${d.name}</h3><p>${d.description}</p><strong>${d.price}</strong></div></article>`).join('')}
function renderGallery(){const items=Array.isArray(menuData.gallery)?menuData.gallery:[];const gallery=document.querySelector('.gallery-grid');if(!gallery)return;gallery.innerHTML=items.map((item,i)=>`<div class="gallery-image gallery-${i+1}" role="img" aria-label="${item.alt||'Restaurant image'}"><img src="${item.image}" alt="${item.alt||''}" loading="lazy" decoding="async"></div>`).join('')}
function renderStory(){if(!menuData.story)return;const s=document.querySelector('.story-content');if(!s)return;const e=s.querySelector('.eyebrow'),h=s.querySelector('h2'),p=s.querySelector('p:not(.eyebrow)');if(e)e.textContent=menuData.story.eyebrow||'';if(h)h.innerHTML=menuData.story.title||'';if(p)p.textContent=menuData.story.copy||''}
const menuToggle=document.querySelector('.menu-toggle'),mobileNav=document.querySelector('.mobile-nav');if(menuToggle&&mobileNav){menuToggle.addEventListener('click',()=>{const o=menuToggle.getAttribute('aria-expanded')==='true';menuToggle.setAttribute('aria-expanded',String(!o));mobileNav.classList.toggle('open',!o)});mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobileNav.classList.remove('open')))}
function renderReservation(){const f=document.querySelector('#reservation-form');if(!f)return;const g=f.querySelector('select[name="guests"]'),t=f.querySelector('select[name="time"]');if(g&&reservationConfig.guests){g.innerHTML='';for(let i=Number(reservationConfig.guests.min||1);i<=Number(reservationConfig.guests.max||8);i++){const o=document.createElement('option');o.value=`${i} guest${i===1?'':'s'}`;o.textContent=o.value;g.appendChild(o)}}if(t&&Array.isArray(reservationConfig.timeSlots))t.innerHTML=reservationConfig.timeSlots.map(x=>`<option>${x}</option>`).join('')}
renderMenu();renderStory();renderGallery();renderReservation();
